# Inserts a blank line between shell prompts
add_newline = true

[character]
format = "ğŸ§  "
vicmd_symbol = "ğŸ§  "
success_symbol = "ğŸŒ•"
error_symbol = "ğŸ¤·â€â™€ï¸"

[username]
style_user = "white bold"
style_root = "red bold"
format = "user: [$user]($style) "
disabled = false

[directory]
# style = "fg:#faee0c"
# style = "fg:#a272ff"
# style = "fg:#A648FF"
style = "fg:#DB5EFF"
truncation_length = 100
truncate_to_repo = false

[python]
symbol = "ğŸ˜ˆ "
python_binary = ["python3"]

[git_branch]
style = "fg:#00ff0d"
symbol = "ğŸ±"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_status]
conflicted = "âš¡ï¸"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
